### ISSUE TITLE
Changing Pinterest layout in userstyle

### ISSUE THREAD

**Issue by uncenter** [catppuccin/userstyles#393]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:pinterest
(@jn-sena)

### Describe your problem.

I saw https://discord.com/channels/907385605422448742/1183384188875968552 about forcing mobile layout and I just took a quick look at the userstyle. Likely unrelated, but I'm curious what this line here is doing: https://github.com/catppuccin/userstyles/blob/main/styles/pinterest/catppuccin.user.css#L78. Usually userstyles should only be changing color-related properties and nothing related to layout.

### What browser(s) are you seeing the problem on?

N/A

**Comment by jn-sena** [comment]
Even though Pinterest has some variables and classes, it's quite messy and they are used in seemingly random pages overall. Background is kind of same. Plus, if I were to set the background of single classes or elements, some of them just cover the others. 

Body `height` is normally set to something small and setting only the background results in this:

![an example image with the line removed, showing a white background instead of intended one.](https://github.com/catppuccin/userstyles/assets/45771313/8f5cd72b-4b13-426e-a284-bb2f58de6a08)

Though might not be ideal, setting the `height` to `auto` solves this and lets me have an easy way to make a *global* background.

Does this raise any problems for you, @uncenter? I can look for alternative ways in my rewrite if so.

(Also, I can't see what you've linked through Discord as I don't use it.)

**Comment by isabelroses** [comment]
> (Also, I can't see what you've linked through Discord as I don't use it.)

In essence the original poster of the issue, found they were being forced into pinterests mobile view, see attached image, when and only when using the userstyle.
![image](https://github.com/catppuccin/userstyles/assets/71222764/721aa896-d2ce-44c5-b124-42f1ae273556)

> Body `height` is normally set to something small and setting only the background results in this

On this note, i can't seem to replicate the issue your having at all

**Comment by jn-sena** [comment]
Seems like the issue with `height` mentioned only occurs when not logged in, for I was not. My mistake. I can remove it when I fix that.

About the forced mobile view, as far as I can tell, Pinterest is using the user agent to switch to that. I get the desktop view if I change my UA to my desktop one (X11, Linux x86_64, Gecko) and refresh while in responsive development mode, regardless of the `height` variable or the actual height:

![a screenshot of responsive mode, with the Pinterest in desktop mode.](https://github.com/catppuccin/userstyles/assets/45771313/cf2c67da-29d2-443e-a56e-5856d40eb4d5)

I don't have any idea what could have gone wrong there.
