### ISSUE TITLE
ChatGPT: "which response do you prefer" unthemed

### ISSUE THREAD

**Issue by Maeglithier** [catppuccin/userstyles#626]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

In the multiple response, the css use a white text color and a white background color. it's impossible to read.

Maybe use a white background with black text or a black background with the default text color.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/58051780/70406cdf-d44e-4fbe-b583-899d73ab2383)

### What browser(s) are you seeing the problem on?

Mozilla Firefox 123.0.1

**Comment by uncenter** [comment]
Please provide steps to recreate. I thought I had fixed that a while back and now I can't seem to find how to get to that screen!

**Comment by Roxas-Alt** [comment]
> Please provide steps to reproduce that UI. I thought I had fixed that a while back and now I can't seem to find how to get to that screen!

I can tell you exactly what I wrote to get to this prompt, but I think it might be a bit random...

[New Chat]

---

Input: Em bash, eu tenho um script que gera a variavel list. Ela é separada da seguinte forma. SSID SECURITY SIGNAL. SECURITY pode ser tanto  quanto  (Considere que vazio também...) e SIGNAL é um numero entre 100 e 0. Eu quero que você pegue a variavel LIST, extraia o numero, faça uma operação para descobrir qual icone vai no lugar e depois substituia em list.

Carlos  72 Rendrix  63 Floresta digital  35

---

output: Claro, você pode usar um script em bash para fazer isso. Aqui está um exemplo de como você poderia fazer:

``` bash
#!/bin/bash

# Função para determinar o ícone com base no sinal
get_icon() {
    signal=$1
    if (( signal >= 80 )); then
        icon=""
    elif (( signal >= 60 )); then
        icon=""
    elif (( signal >= 40 )); then
        icon=""
    elif (( signal >= 20 )); then
        icon=""
    else
        icon=""
    fi
    echo "$icon"
}

# Exemplo de lista
list="Carlos  72 Rendrix  63 Floresta digital  35"

# Separar a lista por espaços em branco
IFS=' ' read -r -a items <<< "$list"

# Loop sobre os itens e modificar o sinal
modified_list=""
for (( i=0; i<${#items[@]}; i+=3 )); do
    ssid="${items[i]}"
    security="${items[i+1]}"
    signal="${items[i+2]}"

    # Obter o ícone com base no sinal
    icon=$(get_icon "$signal")

    # Construir a nova entrada
    modified_entry="$ssid $security $icon"

    # Adicionar à lista modificada
    modified_list+="$modified_entry "

done

# Exibir a lista modificada
echo "$modified_list"
``` 

Este script define uma função chamada get_icon que recebe o sinal como entrada e determina qual ícone usar com base nesse sinal. Em seguida, ele processa a lista fornecida, extrai o sinal de cada entrada, determina o ícone correspondente usando a função get_icon e, finalmente, substitui o ícone na lista original.

---

input: explique como esse loop funciona

``` bash
IFS=' ' read -r -a items <<< "$LIST"

# Loop sobre os itens e modificar o sinal
modified_list=""
for (( i=0; i<${#items[@]}; i+=3 )); do
    ssid="${items[i]}"
    security="${items[i+1]}"
    signal="${items[i+2]}"

    # Obter o ícone com base no sinal
    icon=$(get_icon "$signal")

    # Construir a nova entrada
    modified_entry="$ssid $security $icon"

    # Adicionar à lista modificada
    modified_list+="$modified_entry " 

done
```

---

and then the message asking for the best answer appears.

**Comment by uncenter** [comment]
Sweet thanks. I was unable to repro but I'll merge a PR that fixes it :)

**Comment by enderprism** [comment]
ok so the issue is that these buttons have the `.bg-white` class so they use the text color as their background color and that's why they're unreadable. i don't know html and css enough to target them specifically and not other elements of this class.
i don't know if this class is used in other elements of the page but if it isn't we can modify its `background-color` to `--gray-700` which looks like this:

<details><summary>Code snippet</summary>
<p>

```css
.bg-white {
  background-color: var(--ctp-overlay0);
}
```

</p>
</details> 

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/catppuccin/userstyles/assets/76617157/fc2452bf-ab85-48cf-b0ce-f73e43b15209)

</p>
</details>

**Comment by uncenter** [comment]
I'd like to avoid changing specific elements, due to the nature of ChatGPT using TailwindCSS. I'm guessing we are missing a ["dark mode override"](https://github.com/catppuccin/userstyles/blob/f9e3916bd006182f05806e117ba07e3dd6ffd13c/styles/chatgpt/catppuccin.user.css#L872-L907) class or something like that? Could you share the HTML of those elements?
